# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{houdini-rails}
  s.version = "0.1.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Chris Conley"]
  s.date = %q{2010-08-06}
  s.description = %q{Rails plugin for interacting with the Houdini Mechanical Turk API}
  s.email = %q{chris@chrisconley.me}
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    ".gitignore",
     "MIT-LICENSE",
     "README",
     "Rakefile",
     "VERSION",
     "app/controllers/houdini/postbacks_controller.rb",
     "config/routes.rb",
     "houdini-rails.gemspec",
     "init.rb",
     "install.rb",
     "lib/houdini.rb",
     "lib/houdini/base.rb",
     "lib/houdini/model.rb",
     "lib/houdini/task.rb",
     "spec/controllers/houdini/postbacks_controller_spec.rb",
     "spec/integration/postbacks_test.rb",
     "spec/rails_app/README",
     "spec/rails_app/Rakefile",
     "spec/rails_app/app/controllers/application_controller.rb",
     "spec/rails_app/app/helpers/application_helper.rb",
     "spec/rails_app/app/models/post.rb",
     "spec/rails_app/app/views/posts/houdini_template.html.haml",
     "spec/rails_app/config/boot.rb",
     "spec/rails_app/config/database.yml",
     "spec/rails_app/config/environment.rb",
     "spec/rails_app/config/environments/development.rb",
     "spec/rails_app/config/environments/production.rb",
     "spec/rails_app/config/environments/test.rb",
     "spec/rails_app/config/initializers/backtrace_silencers.rb",
     "spec/rails_app/config/initializers/inflections.rb",
     "spec/rails_app/config/initializers/mime_types.rb",
     "spec/rails_app/config/initializers/new_rails_defaults.rb",
     "spec/rails_app/config/initializers/session_store.rb",
     "spec/rails_app/config/locales/en.yml",
     "spec/rails_app/config/routes.rb",
     "spec/rails_app/db/migrate/20100517231810_create_posts.rb",
     "spec/rails_app/db/seeds.rb",
     "spec/rails_app/doc/README_FOR_APP",
     "spec/rails_app/log/development.log",
     "spec/rails_app/log/production.log",
     "spec/rails_app/log/server.log",
     "spec/rails_app/public/404.html",
     "spec/rails_app/public/422.html",
     "spec/rails_app/public/500.html",
     "spec/rails_app/public/favicon.ico",
     "spec/rails_app/public/images/rails.png",
     "spec/rails_app/public/index.html",
     "spec/rails_app/public/javascripts/application.js",
     "spec/rails_app/public/javascripts/controls.js",
     "spec/rails_app/public/javascripts/dragdrop.js",
     "spec/rails_app/public/javascripts/effects.js",
     "spec/rails_app/public/javascripts/prototype.js",
     "spec/rails_app/public/robots.txt",
     "spec/rails_app/script/about",
     "spec/rails_app/script/console",
     "spec/rails_app/script/dbconsole",
     "spec/rails_app/script/destroy",
     "spec/rails_app/script/generate",
     "spec/rails_app/script/performance/benchmarker",
     "spec/rails_app/script/performance/profiler",
     "spec/rails_app/script/plugin",
     "spec/rails_app/script/runner",
     "spec/rails_app/script/server",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "spec/test_helper.rb",
     "tasks/houdini_tasks.rake",
     "uninstall.rb"
  ]
  s.homepage = %q{http://github.com/chrisconley/houdini-rails}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Rails plugin for interacting with the Houdini Mechanical Turk API}
  s.test_files = [
    "spec/controllers/houdini/postbacks_controller_spec.rb",
     "spec/integration/postbacks_test.rb",
     "spec/rails_app/app/controllers/application_controller.rb",
     "spec/rails_app/app/helpers/application_helper.rb",
     "spec/rails_app/app/models/post.rb",
     "spec/rails_app/config/boot.rb",
     "spec/rails_app/config/environment.rb",
     "spec/rails_app/config/environments/development.rb",
     "spec/rails_app/config/environments/production.rb",
     "spec/rails_app/config/environments/test.rb",
     "spec/rails_app/config/initializers/backtrace_silencers.rb",
     "spec/rails_app/config/initializers/inflections.rb",
     "spec/rails_app/config/initializers/mime_types.rb",
     "spec/rails_app/config/initializers/new_rails_defaults.rb",
     "spec/rails_app/config/initializers/session_store.rb",
     "spec/rails_app/config/routes.rb",
     "spec/rails_app/db/migrate/20100517231810_create_posts.rb",
     "spec/rails_app/db/seeds.rb",
     "spec/spec_helper.rb",
     "spec/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<spec>, [">= 1.3.0"])
    else
      s.add_dependency(%q<spec>, [">= 1.3.0"])
    end
  else
    s.add_dependency(%q<spec>, [">= 1.3.0"])
  end
end

